### ISSUE TITLE
TypeError: Cannot read property 'add' of undefined

### ISSUE THREAD

**Issue by VladoDemcak** [baslr/arangochair#11]
We are using the latest arangodb version (official docker image for arangodb) and we are getting following error:

This is simple info taken from arangodb dashboards:

<img width="1503" alt="screen shot 2019-01-08 at 2 46 02 pm" src="https://user-images.githubusercontent.com/5232606/50834457-583bb780-1354-11e9-87a7-078579f5e99b.png">

```
Currently listening #0 subscribers
/notification-api/node_modules/arangochair/index.js:152
                                txns.get(tid).add([type,entry.slice(idx0+14)]);
                                             ^

TypeError: Cannot read property 'add' of undefined
    at req.get (/notification-api/node_modules/arangochair/index.js:152:46)
    at HttpRequest.handleResponse (/notification-api/node_modules/request-easy/request.js:172:9)
    at rawRequest (/notification-api/node_modules/request-easy/request.js:100:16)
    at IncomingMessage.res.on (/notification-api/node_modules/request-easy/rawRequest.js:87:21)
    at emitNone (events.js:111:20)
    at IncomingMessage.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1056:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
```

**Comment by sudeepvd** [comment]
+1

**Comment by VladoDemcak** [comment]
@sudeepvd we tried some of the forks of arangochair because this repo is dead. And fortunately the [layro01/arangochair](https://github.com/layro01/arangochair)'s fork worked. You can use it in your package.json as follows:
```
"dependencies": {
    "arangochair": "layro01/arangochair"
```

I dont know why the owner of the repo ignores PR and issues but at least we have the working fork. plz let me know if this helped.

**Comment by sudeepvd** [comment]
@VladoDemcak  : It worked. Thanks for your quick turnaround.
